# Generated by Django 3.2.25 on 2026-02-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField()),
                ('about_img1', models.ImageField(blank=True, upload_to='about/')),
                ('about_img2', models.ImageField(blank=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('footer_text', models.CharField(max_length=500)),
                ('hero_img1', models.ImageField(blank=True, upload_to='index/')),
                ('hero_img2', models.ImageField(blank=True, upload_to='index/')),
                ('hero_img3', models.ImageField(blank=True, upload_to='index/')),
                ('newsletter_img', models.ImageField(blank=True, upload_to='index/')),
            ],
        ),
        migrations.CreateModel(
            name='ChooseUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_class', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=50)),
                ('reason_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='projects/')),
                ('name_of_project', models.CharField(max_length=100)),
                ('number_of_project', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_intro', models.TextField(blank=True)),
                ('service', models.CharField(max_length=50)),
                ('service_detail', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='service/')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('twitter', 'Twitter'), ('instagram', 'Instagram'), ('linkedin', 'Linkedin'), ('youtube', 'Youtube')], max_length=50, unique=True)),
                ('url', models.URLField()),
                ('icon_class', models.CharField(max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_img', models.ImageField(blank=True, upload_to='index/')),
                ('profession', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('fb', models.URLField()),
                ('x', models.URLField()),
                ('ig', models.URLField()),
                ('ln', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='index/')),
                ('testimony', models.CharField(max_length=50)),
                ('testimony_text', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
